package com.yutao.flooow.core.exception

class TaskValidateException(
    val msg: String
): TaskException(msg) {
}
